version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: springBasic-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes: # 데이터를 보관하기 위해
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: